// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: addRefreshToken.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRefreshToken = `-- name: AddRefreshToken :exec
INSERT INTO refresh_tokens (
  token, created_at, updated_at, user_id, experies_at  
) VALUES ( $1, $2, $3, $4, $5 )
`

type AddRefreshTokenParams struct {
	Token      string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uuid.UUID
	ExperiesAt time.Time
}

func (q *Queries) AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, addRefreshToken,
		arg.Token,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.ExperiesAt,
	)
	return err
}
