// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: setIsRedChirpyUser.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const setIsRedChirpyUser = `-- name: SetIsRedChirpyUser :exec
update users
set is_chirpy_red = $1
where id = $2
`

type SetIsRedChirpyUserParams struct {
	IsChirpyRed sql.NullBool
	ID          uuid.UUID
}

func (q *Queries) SetIsRedChirpyUser(ctx context.Context, arg SetIsRedChirpyUserParams) error {
	_, err := q.db.ExecContext(ctx, setIsRedChirpyUser, arg.IsChirpyRed, arg.ID)
	return err
}
